### ISSUE TITLE
waiting for javascript

### ISSUE THREAD

**Issue by sciphy-maker** [ItalikDev/H5P-Joomla#1]
Hello,
I installed the h5p package on my joomla site (sciphy.fr).
It's in joomla 4.4.9 and php 8.1.29.
The installation seems working, but when i try to add a new content (or other link), it's not possible and "waiting for javascript" is indicated.
I tried with firefox and chrome, and javascript is enable.
![issue h5p](https://github.com/user-attachments/assets/7eee8439-5f06-4abf-81dc-78fa5715fe97)
Thanks a lot for your help !
Damien

**Comment by ItalikDev** [comment]
Hi!
What web server is installed. apache, nginx or other?

**Comment by sciphy-maker** [comment]
Hi !
Thanks for your help !
the site is hosted by OVH, I don't know what server web is installed, but I also tried with Wamp (Apache), the problem is the same.

**Comment by ItalikDev** [comment]
I looked.
You have Apache server.
Check in your server folder: /libraries/h5p
the presence of the file: .htaccess

On request:
http://sciphy.fr/libraries/h5p/h5p-php-library/js/h5p.js
Answer: 
Forbidden
You don't have permission to access this resource.

if the file is present, then
most likely you have a cascade running:
nginx - apache
You need to configure web server access to subfolders in the directory: /libraries/h5p/

e.g. for nginx server set in config file you web server: 

        location ^~/libraries/h5p/ {
            allow all;
        }

if Apache server 2.0-2.2 then
change file 
/libraries/h5p/.htaccess
to 

```
# Apache 2.4+
<IfModule mod_authz_core.c>
  Require all granted
</IfModule>

# Apache 2.0-2.2
<IfModule !mod_authz_core.c>
  Allow from all
</IfModule>
```

**Comment by sciphy-maker** [comment]
Great !!!
It works ! Thanks a lot !
The htaccess file not existed, so I created it, and copied the code.
Thanks for your great job !
