### ISSUE TITLE
Results of logged users

### ISSUE THREAD

**Issue by sciphy-maker** [ItalikDev/H5P-Joomla#2]
Hi !
The plugin works, I can now create or download new contents and add them in articles.
However, it seems it would be possible to register logged users's results. I can't do that. I tried with a logged in joomla user, results don't appear in "my results".
Is it joomla users ? Or h5p.org users ?
I do something wrong ?
Thanks for your helpful job !
Damien (sciphy.fr)

**Comment by ItalikDev** [comment]
Hi!
In "My results" shows only all results of the currently logged in user in the admin panel.
To view the results of H5P content, you must use the link "Results" in the tab "All H5P Content".
No H5P users all are Joomla users.

**Comment by sciphy-maker** [comment]
Hi, 
thanks ! It works !
I'd search more, sorry.
