### ISSUE TITLE
"waiting for javascript" 

### ISSUE THREAD

**Issue by amukamd** [ItalikDev/H5P-Joomla#3]
Hello,

I installed h5p component, plugins and libraries for joomla from github on my site.

It seems it works, but "waiting for javascript" (printscreen is joined) is indicated.

the site is in joomla 5.2.1, php 8.2.15

Tried with firefox and chrome, javascript is enable.

Please, can you help me ?

Thanks a lot !

**Comment by ItalikDev** [comment]
Hi!
In current version 1.02 not create file in path: /libraries/h5p/.htaccess
download: https://github.com/ItalikDev/H5P-Joomla/blob/master/lib_h5p/.htaccess
and place to  /libraries/h5p.

It will be fixed in the next version.

Vitalii.

**Comment by amukamd** [comment]
It works ! Thanks a lot !
