### ISSUE TITLE
H5p, joomla and userpoints

### ISSUE THREAD

**Issue by sciphy-maker** [ItalikDev/H5P-Joomla#4]
Hi,

I hope i'm in the right part for this question.

For many years, I have a joomla site for my students called sciphy.fr, in which I purpose them little scientific articles, and corrections of activities, but also interactive activities. For the moment, I've used ARI quiz, but I discovered the great H5p who does a lot more !!!

The site use also the component Userpoints, actually developped by Martin Bampton (https://remository.com)/, which allows students to win points when they do quizzes. That works very well, and they can do challenges and win medals, etc .. it's very motivating for them !

So, I've installed the H5P module on this joomla site thanks to your github package. It works, and I can create great activities with H5P for my students.

I've contacted Martin Brampton, who helped me to integrate ari quiz whith UserPoints (Thanks a lot to him !), for doing the same with H5P. Here is his response :

"I'm not sure it is possible for me to integrate h5p with UserPoints without making changes to h5p. But I'm not familiar with its code, and any changes I made would be overwritten as soon as a new version appears.

The best solution is for h5p to incorporate integration with UserPoints. The changes would be easy for the developers of h5p to implement. There is documentation at https://docs.black-sheep-research.com/userpoints:developer and I am always willing to provide support for people building links to UserPoints."

So I contacted the H5P team, who answered me :

"Sorry to say that you're not at the right place. The H5P integration for Joomla was not created by H5P Group (there's a very old one, but it is not working anymore). I assume you are referring toh ttps://github.com/ItalikDev/H5P-Joomla, and you should reach out to the maintainer of that plugin. You can, for instance, raise an issue on github."

So, I do ! Would it be possible ? It would be great for my students and me, but also for userPoints, github, H5P and Joomla ! I think.

Thanks a lot to think about this !

Damien (for sciphy.fr)

**Comment by ItalikDev** [comment]
Hi,

check how it works: https://github.com/ItalikDev/plg_h5p_userpoints/releases

Vitalii
